(function(window, angular, undefined){
	'use strict';
	var app = angular.module('KaisaApp',['common']);

	app.controller('BodyController',['$scope','$window','$timeout','$interval',function($scope,$window,$timeout,$interval){
		$scope.page = {
			idx : 2
		};
		$scope.encodeList = [
			{encode: '-' , decode : '&#00;-&#08;' , decode2 : '-' , description :'사용하지 않음'},
			{encode: 'space' , decode : '&#09;' , decode2 : '-' , description :'수평탭'},
			{encode: 'space' , decode : '&#10;' , decode2 : '-' , description :'줄 삽입'},
			{encode: '-' , decode : '&#11;-&#31;' , decode2 : '-' , description :'사용하지 않음'},
			{encode: 'space' , decode : '&#32;' , decode2 : '-' , description :'여백'},
			{encode: '!' , decode : '&#33;' , decode2 : '-' , description :'느낌표'},
			{encode: '\"' , decode : '&#34;' , decode2 : '&quot;' , description :'따옴표'},
			{encode: '#' , decode : '&#35;' , decode2 : '-' , description :'숫자기호'},
			{encode: '$' , decode : '&#36;' , decode2 : '-' , description :'달러'},
			{encode: '%' , decode : '&#37;' , decode2 : '-' , description :'백분율 기호'},
			{encode: '&' , decode : '&#38;' , decode2 : '&amp;' , description :'Ampersand'},
			{encode: '\'' , decode : '&#39;' , decode2 : '-' , description :'작은 따옴표'},
			{encode: '(' , decode : '&#40;' , decode2 : '-' , description :'왼쪽 괄호'},
			{encode: ')' , decode : '&#41;' , decode2 : '-' , description :'오른쪽 괄호'},
			{encode: '*' , decode : '&#42;' , decode2 : '-' , description :'아스트릭'},
			{encode: '#ERROR!' , decode : '&#43;' , decode2 : '-' , description :'더하기 기호'},
			{encode: ',' , decode : '&#44;' , decode2 : '-' , description :'쉼표'},
			{encode: '-' , decode : '&#45;' , decode2 : '-' , description :'Hyphen'},
			{encode: '.' , decode : '&#46;' , decode2 : '-' , description :'마침표'},
			{encode: '/' , decode : '&#47;' , decode2 : '-' , description :'Solidus (slash)'},
			{encode: '0 - 9' , decode : '&#48;-&#57;' , decode2 : '-' , description :'0부터 9까지'},
			{encode: ':' , decode : '&#58;' , decode2 : '-' , description :'콜론'},
			{encode: ';' , decode : '&#59;' , decode2 : '-' , description :'세미콜론'},
			{encode: '<' , decode : '&#60;' , decode2 : '&lt;' , description :'보다 작은'},
			{encode: '#ERROR!' , decode : '&#61;' , decode2 : '-' , description :'등호'},
			{encode: '>' , decode : '&#62;' , decode2 : '&gt;' , description :'보다 큰'},
			{encode: '?' , decode : '&#63;' , decode2 : '-' , description :'물음표'},
			{encode: '@' , decode : '&#64;' , decode2 : '-' , description :'Commercial at'},
			{encode: 'A - Z' , decode : '&#65;-&#90;' , decode2 : '-' , description :'A부터 Z까지'},
			{encode: '[' , decode : '&#91;' , decode2 : '-' , description :'왼쪽 대괄호'},
			{encode: '\\' , decode : '&#92;' , decode2 : '-' , description :'역슬래쉬'},
			{encode: ']' , decode : '&#93;' , decode2 : '-' , description :'오른쪽 대괄호'},
			{encode: '^' , decode : '&#94;' , decode2 : '-' , description :'탈자부호'},
			{encode: '_' , decode : '&#95;' , decode2 : '-' , description :'수평선'},
			{encode: '`' , decode : '&#96;' , decode2 : '-' , description :'Acute accent'},
			{encode: 'a - z' , decode : '&#97;-&#122;' , decode2 : '-' , description :'a부터 z까지'},
			{encode: '{' , decode : '&#123;' , decode2 : '-' , description :'왼쪽 중괄호'},
			{encode: '|' , decode : '&#124;' , decode2 : '-' , description :'수직선'},
			{encode: '}' , decode : '&#125;' , decode2 : '-' , description :'오른쪽 중괄호'},
			{encode: '~' , decode : '&#126;' , decode2 : '-' , description :'꼬리표'},
			{encode: '-' , decode : '&#127;-&#159;' , decode2 : '-' , description :'사용하지 않음'},
			{encode: '' , decode : '&#160;' , decode2 : '&nbsp;' , description :'Non-breaking space'},
			{encode: '¡' , decode : '&#161;' , decode2 : '&iexcl;' , description :'거꾸로된 느낌표'},
			{encode: '￠' , decode : '&#162;' , decode2 : '&cent;' , description :'센트 기호'},
			{encode: '￡' , decode : '&#163;' , decode2 : '&pound;' , description :'파운드'},
			{encode: '¤' , decode : '&#164;' , decode2 : '&curren;' , description :'현재 환율'},
			{encode: '￥' , decode : '&#165;' , decode2 : '&yen;' , description :'엔'},
			{encode: '|' , decode : '&#166;' , decode2 : '&brvbar;' , description :'끊어진 수직선'},
			{encode: '§' , decode : '&#167;' , decode2 : '&sect;' , description :'섹션 기호'},
			{encode: '¨' , decode : '&#168;' , decode2 : '&uml;' , description :'움라우트'},
			{encode: 'ⓒ' , decode : '&#169;' , decode2 : '&copy;' , description :'저작권'},
			{encode: 'ª' , decode : '&#170;' , decode2 : '&ordf;' , description :'Feminine ordinal'},
			{encode: '≪' , decode : '&#171;' , decode2 : '&laquo;' , description :'왼쪽 꺾인 괄호'},
			{encode: '￢' , decode : '&#172;' , decode2 : '&not;' , description :'부정'},
			{encode: '' , decode : '&#173;' , decode2 : '&shy;' , description :'Soft hyphen'},
			{encode: '?' , decode : '&#174;' , decode2 : '&reg;' , description :'등록상표'},
			{encode: '&hibar;' , decode : '&#175;' , decode2 : '&macr;' , description :'Macron accent'},
			{encode: '°' , decode : '&#176;' , decode2 : '&deg;' , description :'Degree sign'},
			{encode: '±' , decode : '&#177;' , decode2 : '&plusmn;' , description :'Plus or minus'},
			{encode: '²' , decode : '&#178;' , decode2 : '&sup2;' , description :'Superscript two'},
			{encode: '³' , decode : '&#179;' , decode2 : '&sup3;' , description :'Superscript three'},
			{encode: '´' , decode : '&#180;' , decode2 : '&acute;' , description :'Acute accent'},
			{encode: 'μ' , decode : '&#181;' , decode2 : '&micro;' , description :'Micro sign (Mu)'},
			{encode: '¶' , decode : '&#182;' , decode2 : '&para;' , description :'문단기호'},
			{encode: '·' , decode : '&#183;' , decode2 : '&middot;' , description :'Middle dot'},
			{encode: '¸' , decode : '&#184;' , decode2 : '&cedil;' , description :'Cedilla'},
			{encode: '¹' , decode : '&#185;' , decode2 : '&sup1;' , description :'Superscript one'},
			{encode: 'º' , decode : '&#186;' , decode2 : '&ordm;' , description :'Masculine ordinal'},
			{encode: '≫' , decode : '&#187;' , decode2 : '&raquo;' , description :'오른쪽 꺾인 괄호'},
			{encode: '¼' , decode : '&#188;' , decode2 : '&frac14;' , description :'4분의 1'},
			{encode: '½' , decode : '&#189;' , decode2 : '&frac12;' , description :'2분의 1'},
			{encode: '¾' , decode : '&#190;' , decode2 : '&frac34;' , description :'4분의 3'},
			{encode: '¿' , decode : '&#191;' , decode2 : '&iquest;' , description :'거꾸로된 물음표'},
			{encode: 'A' , decode : '&#192;' , decode2 : '&Agrave;' , description :'Capital A, grave accent'},
			{encode: 'A' , decode : '&#193;' , decode2 : '&Aacute;' , description :'Capital A, acute accent'},
			{encode: 'A' , decode : '&#194;' , decode2 : '&Acirc;' , description :'Capital A, circumflex accent'},
			{encode: 'A' , decode : '&#195;' , decode2 : '&Atilde;' , description :'Capital A, tilde'},
			{encode: 'A' , decode : '&#196;' , decode2 : '&Auml;' , description :'Capital A, dieresis or umlaut mark'},
			{encode: 'A' , decode : '&#197;' , decode2 : '&Aring;' , description :'Capital A, ring (Angstrom)'},
			{encode: 'Æ' , decode : '&#198;' , decode2 : '&AElig;' , description :'Capital AE diphthong (ligature)'},
			{encode: 'C' , decode : '&#199;' , decode2 : '&Ccedil;' , description :'Capital C, cedilla'},
			{encode: 'E' , decode : '&#200;' , decode2 : '&Egrave;' , description :'Capital E, grave accent'},
			{encode: 'E' , decode : '&#201;' , decode2 : '&Eacute;' , description :'Capital E, acute accent'},
			{encode: 'E' , decode : '&#202;' , decode2 : '&Ecirc;' , description :'Capital E, circumflex accent'},
			{encode: 'E' , decode : '&#203;' , decode2 : '&Euml;' , description :'Capital E, dieresis or umlaut mark'},
			{encode: 'I' , decode : '&#204;' , decode2 : '&Igrave;' , description :'Capital I, grave accent'},
			{encode: 'I' , decode : '&#205;' , decode2 : '&Iacute;' , description :'Capital I, acute accent'},
			{encode: 'I' , decode : '&#206;' , decode2 : '&Icirc;' , description :'Capital I, circumflex accent'},
			{encode: 'I' , decode : '&#207;' , decode2 : '&Iuml;' , description :'Capital I, dieresis or umlaut mark'},
			{encode: 'Ð' , decode : '&#208;' , decode2 : '&ETH;' , description :'Capital Eth, Icelandic'},
			{encode: 'N' , decode : '&#209;' , decode2 : '&Ntilde;' , description :'Capital N, tilde'},
			{encode: 'O' , decode : '&#210;' , decode2 : '&Ograve;' , description :'Capital O, grave accent'},
			{encode: 'O' , decode : '&#211;' , decode2 : '&Oacute;' , description :'Capital O, acute accent'},
			{encode: 'O' , decode : '&#212;' , decode2 : '&Ocirc;' , description :'Capital O, circumflex accent'},
			{encode: 'O' , decode : '&#213;' , decode2 : '&Otilde;' , description :'Capital O, tilde'},
			{encode: 'O' , decode : '&#214;' , decode2 : '&Ouml;' , description :'Capital O, dieresis or umlaut mark'},
			{encode: '×' , decode : '&#215;' , decode2 : '&times;' , description :'Multiply sign'},
			{encode: 'Ø' , decode : '&#216;' , decode2 : '&Oslash;' , description :'width="130"Capital O, slash'},
			{encode: 'U' , decode : '&#217;' , decode2 : '&Ugrave;' , description :'Capital U, grave accent'},
			{encode: 'U' , decode : '&#218;' , decode2 : '&Uacute;' , description :'Capital U, acute accent'},
			{encode: 'U' , decode : '&#219;' , decode2 : '&Ucirc;' , description :'Capital U, circumflex accent'},
			{encode: 'U' , decode : '&#220;' , decode2 : '&Uuml;' , description :'Capital U, dieresis or umlaut mark'},
			{encode: 'Y' , decode : '&#221;' , decode2 : '&Yacute;' , description :'Capital Y, acute accent'},
			{encode: 'Þ' , decode : '&#222;' , decode2 : '&THORN;' , description :'Capital Thorn, Icelandic'},
			{encode: 'ß' , decode : '&#223;' , decode2 : '&szlig;' , description :'Small sharp s, German (sz ligature)'},
			{encode: 'a' , decode : '&#224;' , decode2 : '&agrave;' , description :'Small a, grave accent'},
			{encode: 'a' , decode : '&#225;' , decode2 : '&aacute;' , description :'Small a, acute accent'},
			{encode: 'a' , decode : '&#226;' , decode2 : '&acirc;' , description :'Small a, circumflex accent'},
			{encode: 'a' , decode : '&#227;' , decode2 : '&atilde;' , description :'Small a, tilde'},
			{encode: 'a' , decode : '&#228;' , decode2 : '&auml;' , description :'Small a, dieresis or umlaut mark'},
			{encode: 'a' , decode : '&#229;' , decode2 : '&aring;' , description :'Small a, ring'},
			{encode: 'æ' , decode : '&#230;' , decode2 : '&aelig;' , description :'Small ae diphthong (ligature)'},
			{encode: 'c' , decode : '&#231;' , decode2 : '&ccedil;' , description :'Small c, cedilla'},
			{encode: 'e' , decode : '&#232;' , decode2 : '&egrave;' , description :'Small e, grave accent'},
			{encode: 'e' , decode : '&#233;' , decode2 : '&eacute;' , description :'Small e, acute accent'},
			{encode: 'e' , decode : '&#234;' , decode2 : '&ecirc;' , description :'Small e, circumflex accent'},
			{encode: 'e' , decode : '&#235;' , decode2 : '&euml;' , description :'Small e, dieresis or umlaut mark'},
			{encode: 'i' , decode : '&#236;' , decode2 : '&igrave;' , description :'Small i, grave accent'},
			{encode: 'i' , decode : '&#237;' , decode2 : '&iacute;' , description :'Small i, acute accent'},
			{encode: 'i' , decode : '&#238;' , decode2 : '&icirc;' , description :'Small i, circumflex accent'},
			{encode: 'i' , decode : '&#239;' , decode2 : '&iuml;' , description :'Small i, dieresis or umlaut mark'},
			{encode: 'ð' , decode : '&#240;' , decode2 : '&eth;' , description :'Small eth, Icelandic'},
			{encode: 'n' , decode : '&#241;' , decode2 : '&ntilde;' , description :'Small n, tilde'},
			{encode: 'o' , decode : '&#242;' , decode2 : '&ograve;' , description :'Small o, grave accent'},
			{encode: 'o' , decode : '&#243;' , decode2 : '&oacute;' , description :'Small o, acute accent'},
			{encode: 'o' , decode : '&#244;' , decode2 : '&ocirc;' , description :'Small o, circumflex accent'},
			{encode: 'o' , decode : '&#245;' , decode2 : '&otilde;' , description :'Small o, tilde'},
			{encode: 'o' , decode : '&#246;' , decode2 : '&ouml;' , description :'Small o, dieresis or umlaut mark'},
			{encode: '÷' , decode : '&#247;' , decode2 : '&divide;' , description :'Division sign'},
			{encode: 'ø' , decode : '&#248;' , decode2 : '&oslash;' , description :'Small o, slash'},
			{encode: 'u' , decode : '&#249;' , decode2 : '&ugrave;' , description :'Small u, grave accent'},
			{encode: 'u' , decode : '&#250;' , decode2 : '&uacute;' , description :'Small u, acute accent'},
			{encode: 'u' , decode : '&#251;' , decode2 : '&ucirc;' , description :'Small u, circumflex accent'},
			{encode: 'u' , decode : '&#252;' , decode2 : '&uuml;' , description :'Small u, dieresis or umlaut mark'},
			{encode: 'y' , decode : '&#253;' , decode2 : '&yacute;' , description :'Small y, acute accent'},
			{encode: 'þ' , decode : '&#254;' , decode2 : '&thorn;' , description :'Small thorn, Icelandic'},
			{encode: 'y' , decode : '&#255;' , decode2 : '&yuml;' , description :'Small y, dieresis or umlaut mark'}
		];
		
	}]);
})(window,window.angular);